
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmelleqatagovueihpre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZWxsZXFhdGFnb3Z1ZWlocHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTExNDQsImV4cCI6MjA1ODc2NzE0NH0.2CT4M8T9sgNyC3WFssMCPBKNcKHAzzaOe8iYRMhRnlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
